openapi: 3.0.3
info:
  title: Open-API Serverless Scaffold
  description: This is a baseline open-api.yaml for scaffolding new projects
  contact:
    name: Jason Chambers
  license:
    name: MIT
    url: 'https://opensource.org/license/mit/'
  version: '1.0'
servers:
  - url: 'http://localhost:3000/api'
    description: Localhost
paths:
  /facts:
    get:
      summary: Fetch a random fact of the day
      description: >-
        Ask the server to say hello to you. Don't forget the "name" query param,
        which is required. Try it without if you want to see a 400 error.
      operationId: facts_get
      parameters:
        - name: filter_word
          in: query
          description: >-
            Filter facts, such that only facts that contain this word can be
            returned
          schema:
            type: string
            minLength: 1
            maxLength: 255
          example: penguin
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  fact:
                    type: string
                    description: A random fact as a string of text
                    example: >-
                      The deepest underwater penguin dive is 1,772 feet by an
                      Emperor Penguin
                nullable: false
      security: []
      servers:
        - url: 'http://localhost:3000'
          description: For use in local development
    summary: Random Fact
    description: Use this endpoint to get a random fact
components:
  schemas:
    fact:
      type: string

