service: chatGPT-Hello-World

plugins:
  - serverless-prune-plugin
  - serverless-offline

package:

provider:
  stage: dev
  name: aws
  runtime: nodejs18.x
  region: us-west-2
  memorySize: 128
  timeout: 15
  apiGateway:
    shouldStartNameWithService: true
  environment:
    SLS_STAGE: ${self:custom.stage}
    SLS_REGION: ${self:custom.region}
    SLS_SERVICE: ${self:service}

#  iamRoleStatements: ${file(./cfn/serverless-default-role.yml)}

custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}
  serverless-offline:
    port: 9000
  prune:
    automatic: true
    number: 10
  additionalStacks:
#    vpc: ${file(./cfn/serverless-vpc.yml)}
#    db: ${file(./cfn/serverless-db.yml)}
#    objectStore: ${file(./cfn/serverless-object-store.yml)}
#    auth: ${file(./cfn/serverless-auth.yml)}
#    logging: ${file(./cfn/serverless-logging.yml)}
#    cfn: ${file(./cfn/serverless-cfn.yml)}

functions: ${file(serverless-functions.yml)}

resources:
  Outputs:
    ServiceEndpoint:
      Export:
        Name: ${self:custom.stage}-${self:service}-APIServiceEndpoint
    ServiceEndpointHost:
      Description: "Host of service endpoint"
      Value: {
        "Fn::Join": [
          "",
          [
            {
              "Ref": "ApiGatewayRestApi"
            },
            ".execute-api.",
            {
              "Ref": "AWS::Region"
            },
            ".",
            {
              "Ref": "AWS::URLSuffix"
            }
          ]
        ]
      }
      Export:
        Name: ${self:custom.stage}-${self:service}-APIServiceEndpointHost
