
###
## Basic Test endpoint. Does NOT use open-api.yaml
## Use this to validate the server is online and to rule in/out issues with open-api.yaml
GET http://localhost:3000/test
Accept: application/json

###
GET http://localhost:3000/api/facts
Access-Control-Request-Method: GET
Origin: http://localhost:3003


###
GET http://localhost:3000/api/facts?filter_word=penguin

###
GET http://localhost:3000/.well-known/ai-plugin.json
Access-Control-Request-Method: GET
Origin: http://localhost:3000

###
GET http://localhost:3000/api/openapi.yaml

###
OPTIONS http://localhost:3000/api/openapi.yaml
Access-Control-Request-Method: GET
Origin: http://localhost:3000
